export const userData = [{
        name: "Jan",
        "Active User": 4000,
    },
    {
        name: "Feb",
        "Active User": 3000,
    },
    {
        name: "Mar",
        "Active User": 5000,
    },
    {
        name: "Apr",
        "Active User": 4000,
    },
    {
        name: "May",
        "Active User": 3000,
    },
    {
        name: "Jun",
        "Active User": 2000,
    },
    {
        name: "Jul",
        "Active User": 4000,
    },
    {
        name: "Agu",
        "Active User": 3000,
    },
    {
        name: "Sep",
        "Active User": 4000,
    },
    {
        name: "Oct",
        "Active User": 1000,
    },
    {
        name: "Nov",
        "Active User": 4000,
    },
    {
        name: "Dec",
        "Active User": 3000,
    },
];

export const productData = [{
        name: "Jan",
        "Sales": 4000,
    },
    {
        name: "Feb",
        "Sales": 3000,
    },
    {
        name: "Mar",
        "Sales": 5000,
    },
];

export const userRows = [{
        id: 1,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 2,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 3,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 4,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 5,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 6,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 7,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 8,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 9,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
    {
        id: 10,
        username: "Jon Snow",
        avatar: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        email: "jon@gmail.com",
        status: "active",
        doctor: "Dr. John Doe",
    },
];

export const productRows = [{
        id: 1,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 2,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 3,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 4,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 5,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 6,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 7,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 8,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 9,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
    {
        id: 10,
        name: "Amitesh Kumar",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "Dr. John Doe",
    },
];